### ISSUE TITLE
Which model weights file should I use for anime face detection?

### ISSUE THREAD

**Issue by Xelawk** [barisbatuhan/DASS_Det_Inference#1]
There are so many model files here. What are the specific meanings of *stage1.pth and *stage3.pth, and which model files need to be imported for inference?

**Comment by barisbatuhan** [comment]
Hi,

Stage 1 and Stage 2 are intermediate weights to help the ones who want to replicate my study. If you want to use the best-performing version, I suggest you to use Stage 3 weights, which are created after a supervised fine-tuning process. Among the different variations of Stage 3 weights, `mixdata_finetuned` is created with multiple stylistic drawing images, `icf_finetuned` is created by using iCartoonFace dataset, and `m109_finetuned` is created by using Manga109 dataset. 

If your images are grayscale, then I believe that you will get the best performance by using `m109_finetuned`. Otherwise, both `icf_finetuned` and `mixdata_finetuned` may result in the best performances. You can try both and select one of them.

Best.
